config/routes.rb
Rails.application.routes.draw do
  root             'posts#index'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  get 'send_activation(:id)' => 'sessions#send_activation', as: 'send_activation'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :update, :create, :destroy, :edit]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :create, :destroy, :show] do
    resources :comments, except: :show
    get 'form', to: 'comments#show', as: 'comment_form'
    member do
      get 'like'
    end
  end
  resources :friendships, only: [:index], as: :friends
  post 'request_friend/:id', to: 'friendships#request_friend',   as: :request_friend
  post 'accept_friend/:id',  to: 'friendships#accept_friend',    as: :accept_friend
  post 'reject_friend/:id',  to: 'friendships#reject_friend',    as: :reject_friend
  post 'unfriend/:id',       to: 'friendships#unfriend',  as: :unfriend

  get 'notifications/:id/open_content', to: 'notifications#open_content',
                                        as: :open_content

  get 'notifications', to: 'notifications#index'

  get 'ffinder', to: 'friends_finder#show'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include NotificationsHelper, SessionsHelper
  before_action :set_post

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      create_post_notification @post, "comment"
      respond_to do |format|
        format.html { redirect_to request.referrer || root_path }
        format.js
      end
    else
      flash[:alert] = "Algo ha salido mal con tu comentario. Reintentamos mas tarde?"
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to request.referrer || root_path }
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- #comment -->
<div class="comment" id="comment_<%= post.id %>_<%= comment.id %>">
  <div class="user-name">
    <%= link_to comment.user.pet_name, user_path(comment.user) %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if current_user?(comment.user) %>
    <%= link_to post_comment_path(post, comment),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, rel: "borrar comentario", remote: true do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes_comments', locals: { post: @post} ) %>");

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
$('#likes_<%= @post.id %>').html("<%= j(render partial: 'posts/likes_comments', locals: {post: @post})%>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>

app/views/comments/show.js.erb
$('#comment-form-<%= @post.id %>').toggleClass('hidden');