config/routes.rb
Rails.application.routes.draw do
  root             'posts#index'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  get 'send_activation(:id)' => 'sessions#send_activation', as: 'send_activation'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :update, :create, :destroy, :edit]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :create, :destroy, :show] do
    resources :comments, except: :show
    get 'form', to: 'comments#show', as: 'comment_form'
    member do
      get 'like'
    end
  end
  resources :friendships, only: [:index], as: :friends
  post 'request_friend/:id', to: 'friendships#request_friend',   as: :request_friend
  post 'accept_friend/:id',  to: 'friendships#accept_friend',    as: :accept_friend
  post 'reject_friend/:id',  to: 'friendships#reject_friend',    as: :reject_friend
  post 'unfriend/:id',       to: 'friendships#unfriend',  as: :unfriend

  get 'notifications/:id/open_content', to: 'notifications#open_content',
                                        as: :open_content

  get 'notifications', to: 'notifications#index'

  get 'ffinder', to: 'friends_finder#show'

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :notice_type,
    presence: true

    paginates_per 10

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def open_content
    @notification = Notification.find(params[:id])
    @notification.update read: true
    if @notification.post
      redirect_to post_path @notification.post
    else
      @user = User.find(@notification.notified_by)
      redirect_to @user
    end
  end

  def index
    @notifications = last_notifications.page(params[:page]).per(10)
  end

  private

  def last_notifications
    current_user.notifications.order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def create_post_notification(post, type)
    return if post.user_id == current_user.id
    user = User.find(post.user_id)
    notification = user.notifications.build(
                          user_id: post.user.id,
                          notified_by_id: current_user.id,
                          post_id: post.id,
                          notice_type: type)
    notification.save!
  end

  def create_friend_notification(user, type)
    return if user == current_user
    notification = user.notifications.build(
                          user_id: user.id,
                          notified_by_id: current_user.id,
                          post_id: nil,
                          notice_type: type)
    notification.save!
  end

  def notification_description (notification)
    case notification.notice_type
      when "like"
        return "ha hecho Guau! en tu post"
      when "comment"
        return "ha comentado en tu post"
      when "request"
        return "te ha enviado una solicitud de amistad"
      when "accept_request"
        return "ha aceptado tu solicitud de amistad"
      when "reject_request"
        return "ha rechazado tu solicitud de amistad"
    end
  end
end

app/views/notifications/_notification.html.erb
<li class="<%=notification.read ? 'read' : 'unread' %>">
  <!-- start notification -->
  <%= link_to open_content_path(notification), class: "description" do %>
    <i class="fa fa-users text-aqua"></i>
    <b><%= notification.notified_by.pet_name %></b>
    <%= notification_description(notification) %>
    <br><span class="time-ago">
      <%= time_ago_in_words(notification.created_at) %> ago.
    </span>
  <% end %>
</li>

app/views/notifications/_notifications_menu.html.erb
<% @count = current_user.notifications.where(read: false).count%>
<li class="dropdown notifications-menu">
  <!-- Menu toggle button -->
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="glyphicon glyphicon-flag fa-lg"></i>
    <span class="label label-warning"><%= @count  if @count > 0 %></span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">
      Tienes <%= pluralize @count, 'notificación' %>
      <%= 'nueva'.pluralize(@count) %>
    </li>
    <li>
      <!-- Inner Menu: contains the notifications -->
      <ul class="menu">
        <%= render current_user.notifications.order('created_at DESC').last(5) %>
        <!-- end notification -->
      </ul>
    </li>
    <li class="footer">
      <%= link_to 'Ver todas', notifications_path %>
    </li>
  </ul>
</li>

app/views/notifications/index.html.erb
<%= provide(:title, "Notificationes") %>
<div class=".container">
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <ul class="notification-index-list">
       <%= render @notifications %> 
      </ul>
      <%= paginate @notifications %>
    </div>
  </div>
</div>