config/routes.rb
Rails.application.routes.draw do
  root             'posts#index'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  get 'send_activation(:id)' => 'sessions#send_activation', as: 'send_activation'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :update, :create, :destroy, :edit]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :create, :destroy, :show] do
    resources :comments, except: :show
    get 'form', to: 'comments#show', as: 'comment_form'
    member do
      get 'like'
    end
  end
  resources :friendships, only: [:index], as: :friends
  post 'request_friend/:id', to: 'friendships#request_friend',   as: :request_friend
  post 'accept_friend/:id',  to: 'friendships#accept_friend',    as: :accept_friend
  post 'reject_friend/:id',  to: 'friendships#reject_friend',    as: :reject_friend
  post 'unfriend/:id',       to: 'friendships#unfriend',  as: :unfriend

  get 'notifications/:id/open_content', to: 'notifications#open_content',
                                        as: :open_content

  get 'notifications', to: 'notifications#index'

  get 'ffinder', to: 'friends_finder#show'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  acts_as_votable
  has_attached_file :image, styles: { :medium => "450x400" }
  has_attached_file :video, styles: {
    :medium => { :geometry => "450x400", :format => 'mp4' },
    :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
    }, :processors => [:transcoder]

  scope :for_index, -> (user) {
    ids = user.friends.map {|f| f.id}
    ids << user.id
    where(user_id: ids)
    }

  validates :user_id, presence: true
  # validates :content, presence: true, length: { minimum: 3, maximum: 255 }
  validates_attachment :image, size: { in: 0..1.megabytes }, content_type: { content_type: /\Aimage\/.*\Z/ }
  validates_attachment :video, size: { in: 0..3.megabytes }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper, NotificationsHelper

  before_action :logged_in_user?, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  before_action :set_post, only: [:destroy, :show, :like]

  def index
    return unless logged_in?
    @post = current_user.posts.build
    # @feed_items = current_user.feed.page params[:page]
    @feed_items = Post.for_index(current_user).order('created_at DESC').page params[:page]
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save!
      redirect_to root_url
    else
      flash[:danger] = "Ups, we couldn't post that."
      render :index
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "post deleted"
    redirect_to request.referrer || root_url
  end

  def show
    @post = Post.find(params[:id])
  end

  def like
    if current_user.voted_for? @post
      @post.unliked_by current_user
    else
      @post.liked_by current_user
      create_post_notification @post, "like"
    end
    # binding.pry
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'like' }
    end
    # render json: params
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :video, :title)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  #DONE:50 Display the number of likes as a link
  #DONE:40 open a panel by clicking the number of likes (jQuery Bootstrap)
  #TODO:0 Display the name of likers as links in the opened panel
  #DONE:10 hide and show the comment form

  def display_likers(post)
    list_likers(set_votes(post))
  end

  def display_likes(post)
    count_likers(set_votes(post))
  end

  def liked_post(post)
    return 'primary' if current_user.voted_for? post 
    'default'
  end

  def display_comments(post)
    pluralize post.comments.count, "Comentario"
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.pet_name, user_path(voter), class: 'user-name')
      end
      user_names.to_sentence.html_safe
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    pluralize vote_count, 'Guau'
  end

  def set_votes(post)
    post.votes_for.up.by_type("User")
  end

end

app/views/posts/_like_button.html.erb
<%= link_to ' Guau!', 
  like_post_path(post.id), 
  id: "like_#{post.id}", 
  class: "fa fa-paw btn btn-#{liked_post post}", 
  remote: true 
%>

app/views/posts/_likes_comments.html.erb
<div class="likes">
  <div class="pull-right">
    <% if post.votes_for.count > 0 %>
      <span class="guau-count"><i class="fa fa-paw"></i> <%= display_likes post %></span>
    <% end %>
    <% if post.comments.any? %>
      <span><i class="fa fa-comment"></i> <%= display_comments post %></span>
    <% end %>
  </div>
</div>

app/views/posts/_no_feed.html.erb
<div class="posts-wrapper text-center">
  <h1>There's nothing to see here yet</h1>
  <h3>Post something or follow a friend</h3>
</div>

app/views/posts/_paginator.html.erb
<div class="text-center" id="paginator">
  <%= link_to_next_page @feed_items, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_post.html.erb
<!-- TODO: display "view all" on notifications  -->
<div class="posts-wrapper">
  <div class="post">
    <!-- head of the post -->
    <div class="post-head">
      <div class="post-head-content">
        <%= link_to image_tag(post.user.pet_image.url(:thumb), class: "profile-pic"), post.user %>
        <% if current_user?(post.user) %>
          <%= link_to post_path(post),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, remote: true do %>
            <span class="glyphicon glyphicon-remove delete-post"></span>
          <% end %>
        <% end %>
        <div class="post-header-text">
          <%= link_to post.user.pet_name, user_path(post.user), class: "user-name" %>
          <p class="time-ago"> Posted
            <%= time_ago_in_words(post.created_at) %> ago.
          </p>
        </div>
      </div>
    </div>
<!-- body of the post -->
    <div class="image center-block">
      <%= content_tag('p', post.content, class: 'caption') if post.content%>
      <%= content_tag('p', post.title, class: 'caption') if post.title%>
    </div>
    <div class="image center-block">
      <%= link_to image_tag(post.image.url(:medium), class:'img-responsive'), post_path(post) if post.image.exists?%>
      <%#= link_to video_tag(post.video.url(:medium)), post_path(post) if post.video.exists? %>
    </div>
    <!-- footer of the post -->
    <div class="post-bottom">
      <div class="comment-like-form row">
        <div class="like-button col-md-6">
          <%= render 'posts/like_button', post: post %>
          <%= link_to ' Comentar', post_comment_form_path(post.id),
            id: "comment_#{post.id}", class: "fa fa-comment btn btn-default", remote: true %>
        </div>
        <div class="pull-right col-md-6" id="likes_<%= post.id %>">
          <%= render partial: 'posts/likes_comments', locals: {post: post} %>
        </div>
      </div>
       <!-- Comments section -->
      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments.any? %>
          <div class="paginator" id="#comments-paginator-<%= post.id %>">
            <% unless post.comments.count <= 3 %>
              <%= link_to "Ver todos los comentarios", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
            <% end %>
          </div>
          <%= render post.comments.last(3), post: post %>
        <% end %>
      </div>
    <!-- comment form  -->
    <div class="comment-like-form row hidden" id="comment-form-<%= post.id %>">
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
        <div class="flex-container">
          <%= f.text_area :content, placeholder: 'Haz un comentario...', size: "20x1", class: "comment_content", id: "comment_content_#{post.id}" %>
          <%= f.submit "Publicar", class: "btn btn-primary", id: "post-comment" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class="floaty">
  <ul class="floaty-list">
    <li class="floaty-list-item floaty-list-item--green" id="foaty-text-post">
        <span class="floaty-list-item-label">Writing</span>
        <%= image_tag 'edit_icon.svg', data: { toggle: 'modal', target: '#post_text'}%>
    </li>
    <li class="floaty-list-item floaty-list-item--blue">
      <span class="floaty-list-item-label">Picture</span>
      <%= image_tag 'add-photo.svg', data: { toggle: 'modal', target: '#post_image' }%>
    </li>
  </ul>
  <div class="floaty-btn">
    <span class="floaty-btn-label">
      Post something
    </span>
    <%= image_tag 'paw_icon.svg', class: "floaty-btn-icon absolute-center" %>
  </div>
</div>
<%= render 'post_text' %>
<%= render 'post_image' %>

app/views/posts/_post_image.html.erb
<div class="modal fade" id="post_image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title title" id="myModalLabel">make the world see that image!</h3>
      </div>
      <div class="modal-body">
        <div class="form-wrapper">
          <%= simple_form_for @post,
            html: { class: 'form-horizontal', multipart: true } do |f| %>
            <div class="form-group text-center">
              <%= f.error_notification %>
              <%= f.input :image %>
              <%= f.input :title %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="cancel-post">
                Cancel
              </button>
              <%= f.submit "Post", class: "btn btn-primary sized-btn"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_text.html.erb
<!-- TODO: quitar validacion de contenido de post -->
<div class="modal fade" id="post_text" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title title" id="myModalLabel">bark something!</h3>
      </div>
      <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
        <div class="modal-body">
          <div class="flex-container">
            <%= f.error_notification %>
            <%= f.text_area :content, placeholder: 'Start writing here...',
              class: "post-text", required: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="cancel-post">
            Cancel
          </button>
          <%= f.submit "Post", class: "btn btn-primary sized-btn"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if logged_in? %>
<div class="row">
  <div class="col-md-4">
    <section class="user_info">
      <%= render 'layouts/userinfo_sidebar' %>
    </section>
  </div>
  <aside class="banner-container">
    <div class="right-banner"></div>
  </aside>
  <% if @feed_items.any? %>
    <%= render 'shared/feed' %>
    <%= render 'paginator' %>
  <% else %>
    <%= render 'no_feed' %>
  <% end %>
  <%= render 'post_form'%>
</div>
<% else %>
  <%= render 'layouts/cover_page' %>
<% end %>

app/views/posts/index.js.erb
$('#posts_page').after("<%= escape_javascript(render 'feed')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@feed_items, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
<% if current_user.voted_for? @post %>
  $("#like_<%= @post.id %>").removeClass('btn-default').addClass('btn-primary');
<% else %>
  $("#like_<%= @post.id %>").removeClass('btn-primary').addClass('btn-default');
<% end %>

$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes_comments', locals: { post: @post} ) %>");

app/views/posts/show.html.erb
<% @feed_items = @post%>
<%= render 'shared/feed' %>
<div class="text-center edit-links">
  <%= link_to "Back", posts_path, class: "btn btn-primary" %>
</div>