config/routes.rb
Rails.application.routes.draw do
  root             'posts#index'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  get 'send_activation(:id)' => 'sessions#send_activation', as: 'send_activation'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :update, :create, :destroy, :edit]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :create, :destroy, :show] do
    resources :comments, except: :show
    get 'form', to: 'comments#show', as: 'comment_form'
    member do
      get 'like'
    end
  end
  resources :friendships, only: [:index], as: :friends
  post 'request_friend/:id', to: 'friendships#request_friend',   as: :request_friend
  post 'accept_friend/:id',  to: 'friendships#accept_friend',    as: :accept_friend
  post 'reject_friend/:id',  to: 'friendships#reject_friend',    as: :reject_friend
  post 'unfriend/:id',       to: 'friendships#unfriend',  as: :unfriend

  get 'notifications/:id/open_content', to: 'notifications#open_content',
                                        as: :open_content

  get 'notifications', to: 'notifications#index'

  get 'ffinder', to: 'friends_finder#show'

end

app/views/layouts/_chat_menu.html.erb
<li class="dropdown tasks-menu">
  <!-- Menu Toggle Button -->
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="glyphicon glyphicon-comment fa-lg"></i>
    <!-- <span class="label label-primary">9</span> -->
  </a>
  <ul class="dropdown-menu">
    <li class="header text-center">Chat is coming soon. Stay tuned</li>
  </ul>
</li>

app/views/layouts/_cover_page.html.erb
<div class="background">
  <div class="bg-layer">
    <div class="quotes first-qt">
      <h4>
        <p>
          “When the Man woke up he said, ‘What is Wild Dog doing here?’
          <br>And the Woman said, ‘His name is not Wild Dog any more,
          <br>but the First Friend, because he will be our friend
          <br>for always and always and always.'”
        </p><em>-Rudyard Kipling</em>
      </h4>
    </div>
    <div class="quotes last-qt">
      <h4>
        <p>
          “A dog is the only thing on earth that loves you more than he loves himself.”</p><em>-Josh Billings</em>
      </h4>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%=msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<div class="flash-container">
  <div class="flash alert alert-<%= message_type %>">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
</footer>

app/views/layouts/_header.html.erb
<!-- Main Header -->
<header class="main-header navbar-fixed-top">

  <!-- Logo -->
  <%= link_to root_path, class: "logo" do %>
  <span class="logo-md">
    <%= image_tag 'Paws_logo1.png', alt: 'paws_logo', id: 'logo' %>
  </span>
  <% end %>
  <%= render logged_in? ? 'layouts/logged_header' : 'layouts/login_header'%>
</header>

app/views/layouts/_logged_header.html.erb
<%#DONE:0 Put the settings box under gears icon%>
<!-- Logged-in Right Menu -->
<nav class="navbar navbar-fixed-top" role="navigation">
  <!-- search form (Optional) -->
  <div class="navbar-search-form">
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>
  </div>
  <!-- /.search form -->
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- Friends finder Menu -->
      <%= render 'friends_finder/ffinder_menu' %>

      <!-- Notifications Menu -->
      <%= render 'notifications/notifications_menu' %>

      <!-- Chat Menu -->
      <%= render 'layouts/chat_menu' %>
      <!-- User Account Menu -->
      <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <!-- The user image in the navbar-->
          <%= image_tag @current_user.pet_image.url(:thumb), class: "user-image", alt: "User Image" %>
          <!-- hidden-xs hides the username on small devices so only the image appears. -->
          <span class="hidden-xs">
            <b><%= @current_user.pet_name %></b>
          </span>
        </a>
        <ul class="dropdown-menu">
          <!-- The user image in the menu -->
          <li class="user-header">
            <%= image_tag @current_user.pet_image.url(:small), class: "image-circle" %>
            <p>
              <%= @current_user.pet_name %>
              - <%= @current_user.breed%>
              <small>Member since
                <%= date_in_words(@current_user.created_at) %></small>
            </p>
          </li>
          <!-- Menu Body -->
          <li class="user-body">
            <div class="row">
              <div class="col-xs-4 text-center">
                <%= link_to "Settings", edit_user_path(@current_user) %>
              </div>
              <div class="col-xs-4 text-center">
                <%= link_to "Friends", friends_path %>
              </div>
              <div class="col-xs-4 text-center">
                <%= link_to "Sign Out", "users/#{@current_user.id}", method: :delete,
                  data: { confirm: "Are you sure to delete your profile?" } %>
              </div>
            </div>
            <!-- /.row -->
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <%= link_to "Profile", @current_user, class: "btn btn-default btn-flat" %>
            </div>
            <div class="pull-right">
              <%= link_to "Log Out", logout_path, method: :delete, class: "btn btn-default btn-flat" %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_login_header.html.erb
<!-- no logged options Right Menu -->
<nav class="navbar navbar-static-top" role="navigation">
  <div class="login-menu">
    <%= link_to 'Login', login_path, class: "btn btn-primary btn-lg" %>
    <%= link_to 'Signup', signup_path, class: "btn btn-default-outline btn-lg" %>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_basic_info.html.erb
<%= f.input :pet_name, required: true, autofocus: true, label: false, placeholder: 'My name is...', input_html: { class: 'input-lg form-control' } %>
<%= f.input :email, required: true, autofocus: true, label: false, placeholder: 'My email address is...', input_html: { class: 'input-lg form-control' } %>
<%= f.input :password, required: true, label: false, placeholder: 'My password', input_html: { class: 'input-lg form-control' } %>
<%= f.input :password_confirmation, required: true, label: false, placeholder: 'Confirm my password', input_html: { class: 'input-lg form-control' } %>

app/views/layouts/_userinfo_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <figure class="card">
    <%= image_tag @current_user.pet_image.url(:medium), alt: "Pet Image" %>
    <figcaption>
      <%= image_tag @current_user.human_image.url(:small),class: "profile", alt: "Human Image" %>
      <h3><%= @current_user.pet_name%>
        <%= "| " + @current_user.human_name if @current_user.human_name%>
      </h3>
      <span class="pet-stats">
        <%=@current_user.breed%>
        <%= "- " + (time_ago_in_words @current_user.birthdate) if @current_user.birthdate%>
      </span>
      <p><%= @current_user.bio %></p>
      <div class="flex-container stats-container">
        <ul class="stats">
          <li>
            <%= link_to @current_user, class: "info stats-links" do%>
            <span class="stats-label">Posts</span>
            <span class="stats-value"><%= @current_user.posts.count%></span>
            <% end %>
          </li>
          <li>
            <%= link_to friends_path, class: "info stats-links" do%>
            <span class="stats-label">Friends</span>
            <span class="stats-value"><%=@current_user.friends.count%></span>
            <% end %>
          </li>
        </ul>
      </div>
    </figcaption>
  </figure>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render'layouts/header'%>
    <%= render 'layouts/flash_message'%>
    <div class="<%= " content-wrapper" if true %>">
      <%= yield %>
    </div>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>

app/views/layouts/pop_up.js.erb
// close button
var closeBtn = $('<a href="#" data-rel="back" class="ui-btn-right ui-btn ui-btn-b ui-corner-all ui-btn-icon-notext ui-icon-delete ui-shadow">Close</a>');

// text you get from Ajax
var content = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing. Morbi convallis sem et dui sollicitudin tincidunt.</p>";

// Popup body - set width is optional - append button and Ajax msg
var popup = $("<div/>", {
  "data-role": "popup"
}).css({
  width: $(window).width() / 2.5 + "px",
  padding: 5 + "px"
}).append(closeBtn).append(content);

// Append it to active page
$.mobile.pageContainer.append(popup);

// Create it and add listener to delete it once it's closed
// open it
$("[data-role=popup]").popup({
  dismissible: false,
  history: false,
  theme: "b",
  /* or a */
  positionTo: "window",
  overlayTheme: "b",
  /* "b" is recommended for overlay */
  transition: "pop",
  beforeposition: function () {
    $.mobile.pageContainer.pagecontainer("getActivePage")
      .addClass("blur-filter");
  },
  afterclose: function () {
    $(this).remove();
    $(".blur-filter").removeClass("blur-filter");
  },
  afteropen: function () {
    /* do something */
  }
}).popup("open");